module.exports = [
	{
		subject: 'Fullstack Development Project',
		projectDescription:
			'Develop a fullstack web application with user authentication and data visualization.',
		budget: 3000.0,
		currency: 'EUR',
		availableTime: 'En más de un mes',
		status: 'pending',
	},
	{
		subject: 'Data Analysis and Visualization',
		projectDescription: 'Analyze sales data and create interactive dashboards.',
		budget: 2000.0,
		currency: 'USD',
		availableTime: 'En más de un mes',
		status: 'pending',
	},
	{
		subject: 'Backend API Development',
		projectDescription: 'Develop a RESTful API for a mobile application.',
		budget: 1500.0,
		currency: 'USD',
		availableTime: 'Ahora',
		status: 'pending',
	},
	{
		subject: 'Marketing Campaign Strategy',
		projectDescription: 'Develop a comprehensive marketing strategy for a new product launch.',
		budget: 2500.0,
		currency: 'EUR',
		availableTime: 'En más de un mes',
		status: 'pending',
	},
	{
		subject: 'SEO Optimization',
		projectDescription: 'Optimize website for search engines to increase organic traffic.',
		budget: 1800.0,
		currency: 'ARS',
		availableTime: 'Ahora',
		status: 'pending',
	},
	{
		subject: 'Content Writing',
		projectDescription: 'Write and edit articles for the company blog.',
		budget: 1000.0,
		currency: 'USD',
		availableTime: 'Ahora',
		status: 'pending',
	},
	{
		subject: 'Systems Analysis',
		projectDescription: 'Analyze existing IT systems and recommend improvements.',
		budget: 2200.0,
		currency: 'ARS',
		availableTime: 'En un plazo de varias semanas',
		status: 'pending',
	},
	{
		subject: 'Project Management',
		projectDescription: 'Lead a team to develop a new software feature.',
		budget: 2700.0,
		currency: 'EUR',
		availableTime: 'En un plazo de varias semanas',
		status: 'pending',
	},
	{
		subject: 'UI/UX Design',
		projectDescription: 'Design user interface for a mobile app.',
		budget: 2100.0,
		currency: 'ARS',
		availableTime: 'En un plazo de varias semanas',
		status: 'pending',
	},
	{
		subject: 'Branding Strategy',
		projectDescription: 'Develop a branding strategy for a new company.',
		budget: 3200.0,
		currency: 'USD',
		availableTime: 'Ahora',
		status: 'pending',
	},
	{
		subject: 'Social Media Management',
		projectDescription: 'Manage social media accounts and create content.',
		budget: 1300.0,
		currency: 'ARS',
		availableTime: 'En un plazo de varias semanas',
		status: 'pending',
	},
]
